services:
  - type: web
    name: ayurgenix-service
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: uvicorn ayurgenix.asgi:application --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ayurgenix-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        value: your-generated-secret-key
      - key: DEBUG
        value: "False"
      - key: MODEL_PATH
        value: sshleifer/tiny-gpt2

        
        
    
      - key: ALLOWED_HOSTS
        value: ayurgenix-service.onrender.com
    plan: free
